// Generated by Selenium IDE

using OpenQA.Selenium;
using OpenQA.Selenium.Firefox;

namespace Lab4Selenium;

[TestFixture]
public class AlertTest
{
    [SetUp]
    public void SetUp()
    {
        driver = new FirefoxDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }

    [TearDown]
    public void CleanUp()
    {
        driver.Quit();
        driver.Dispose();
    }

    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;


    [Test]
    public void TestSimpleAlert()
    {
        driver.Navigate().GoToUrl("https://the-internet.herokuapp.com/javascript_alerts");
        driver.FindElement(By.XPath("//button[contains(text(), 'Click for JS Alert')]")).Click();
        driver.SwitchTo().Alert().Accept();
        var resultText = driver.FindElement(By.Id("result")).Text;
        Assert.AreEqual("You successfully clicked an alert", resultText);
    }

    [Test]
    public void TestPresenceOfAlertButtons()
    {
        driver.Navigate().GoToUrl("https://the-internet.herokuapp.com/javascript_alerts");

        var simpleAlertButtonExists =
            driver.FindElements(By.XPath("//button[contains(text(), 'Click for JS Alert')]")).Count > 0;
        Assert.IsTrue(simpleAlertButtonExists);

        var confirmAlertButtonExists =
            driver.FindElements(By.XPath("//button[contains(text(), 'Click for JS Confirm')]")).Count > 0;
        Assert.IsTrue(confirmAlertButtonExists);

        var promptAlertButtonExists =
            driver.FindElements(By.XPath("//button[contains(text(), 'Click for JS Prompt')]")).Count > 0;
        Assert.IsTrue(promptAlertButtonExists);
    }

    [Test]
    public void TestButtonProperties()
    {
        driver.Navigate().GoToUrl("https://the-internet.herokuapp.com/javascript_alerts");

        var alertButton = driver.FindElement(By.XPath("//button[contains(text(), 'Click for JS Alert')]"));

        var buttonText = alertButton.Text;
        Assert.AreEqual("Click for JS Alert", buttonText);

        var isButtonDisplayed = alertButton.Displayed;
        Assert.IsTrue(isButtonDisplayed);
    }
}