// Generated by Selenium IDE

using System.Drawing;
using OpenQA.Selenium;
using OpenQA.Selenium.Firefox;

namespace Lab4Selenium;

[TestFixture]
public class SearchTest
{
    [SetUp]
    public void SetUp()
    {
        driver = new FirefoxDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }

    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
        driver.Dispose();
    }

    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;

    [Test]
    public void SearchSimpleTest()
    {
        driver.Navigate().GoToUrl("https://pl.wikipedia.org/wiki/Wikipedia:Strona_g%C5%82%C3%B3wna");
        driver.Manage().Window.Size = new Size(2208, 1200);
        driver.FindElement(By.Id("searchInput")).Click();
        driver.FindElement(By.Name("search")).Click();
        driver.FindElement(By.Name("search")).SendKeys("selenium");
        driver.FindElement(By.CssSelector(".cdx-button--action-default")).Click();
    }

    [Test]
    public void EnterSimpleTest()
    {
        driver.Navigate().GoToUrl("https://pl.wikipedia.org/wiki/Wikipedia:Strona_g%C5%82%C3%B3wna");
        driver.Manage().Window.Size = new Size(2208, 1200);
        driver.FindElement(By.Id("searchInput")).Click();
        driver.FindElement(By.Name("search")).Click();
        driver.FindElement(By.Name("search")).SendKeys("selenium");
        driver.FindElement(By.Name("search")).SendKeys(Keys.Enter);
    }
}